### PR TITLE
Weekly PR

### PR DESCRIPTION
**Pull request by vedi**

### CODE REVIEW

**Comment by borisspektor** [comment]
@EugeneButusov @vedi please start writing informative commit messages, and not the title of the task.
Did you check that everything builds correctly using the "build_all" script?

**Comment by vedi** [comment]
@borisspektor, 
1. we use common industrial standards for the commit messages, and @refaelos was happy enough about this. Please, solve this with him.
2. the PR is under-code review at the moment, when it passes all the tests, I'll put it as ready for merge.

**Comment by EugeneButusov** [comment]
@borisspektor, checked it, build scripts runs correctly.

**Comment by vedi** [comment]
@borisspektor, @refaelos, it's ready to merge

**Pull request merged**
